{"uid":"fa2c1d05d11af288","name":"Add a Recipe to a Collection -- @1.1 ","fullName":"Collections: Add a Recipe to a Collection","historyId":"064f3a57ed0026516ddf41142463fedd","time":{"start":1667413998612,"stop":1667414015811,"duration":17199},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":true,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"passed","steps":[{"name":"Given User is logged in as username: technical_assignment, password: uhqom-duqmum-tepXe7","time":{"start":1667413998612,"stop":1667414011073,"duration":12461},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Given A Collection with title: Test Collection, exists","time":{"start":1667414011073,"stop":1667414012405,"duration":1332},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Given User is on the Dashboard page","time":{"start":1667414012405,"stop":1667414012430,"duration":25},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks Explore","time":{"start":1667414012430,"stop":1667414012485,"duration":55},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks a Recipe","time":{"start":1667414012486,"stop":1667414013896,"duration":1410},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks kebab icon","time":{"start":1667414013896,"stop":1667414014469,"duration":573},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User hovers on Add to collection","time":{"start":1667414014469,"stop":1667414014757,"duration":288},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Then Collection with title: Test Collection, is present","time":{"start":1667414014757,"stop":1667414014794,"duration":37},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks title: Test Collection","time":{"start":1667414014795,"stop":1667414014848,"duration":53},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks profile icon","time":{"start":1667414014848,"stop":1667414015021,"duration":173},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks Dashboard","time":{"start":1667414015021,"stop":1667414015082,"duration":61},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks Collections tab","time":{"start":1667414015082,"stop":1667414015649,"duration":567},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Then Recipe is visible in Collection","time":{"start":1667414015649,"stop":1667414015698,"duration":49},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Then Delete the Collection","time":{"start":1667414015698,"stop":1667414015811,"duration":113},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"attachments":[],"parameters":[],"stepsCount":14,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"Collections"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"password","value":"uhqom-duqmum-tepXe7"},{"name":"title","value":"Test Collection"},{"name":"username","value":"technical_assignment"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":3,"broken":0,"skipped":0,"passed":3,"unknown":0,"total":6},"items":[{"uid":"8f5c565baa8038d8","reportUrl":"https://timjden.github.io/cinc_assignment/27//#testresult/8f5c565baa8038d8","status":"failed","statusDetails":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55b8883b62c3 <unknown>\n#1 0x55b8881bf83a <unknown>\n#2 0x55b8881f8985 <unknown>\n#3 0x55b8881f8b61 <unknown>\n#4 0x55b888230d14 <unknown>\n#5 0x55b888216f6d <unknown>\n#6 0x55b88822ea50 <unknown>\n#7 0x55b888216d63 <unknown>\n#8 0x55b8881eb7e3 <unknown>\n#9 0x55b8881eca21 <unknown>\n#10 0x55b88840418e <unknown>\n#11 0x55b888407622 <unknown>\n#12 0x55b8883eaaae <unknown>\n#13 0x55b8884082a3 <unknown>\n#14 0x55b8883deecf <unknown>\n#15 0x55b888428588 <unknown>\n#16 0x55b888428706 <unknown>\n#17 0x55b8884428b2 <unknown>\n#18 0x7ff9e8e8f609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x55b8883b62c3 <unknown>\n#1 0x55b8881bf83a <unknown>\n#2 0x55b8881f8985 <unknown>\n#3 0x55b8881f8b61 <unknown>\n#4 0x55b888230d14 <unknown>\n#5 0x55b888216f6d <unknown>\n#6 0x55b88822ea50 <unknown>\n#7 0x55b888216d63 <unknown>\n#8 0x55b8881eb7e3 <unknown>\n#9 0x55b8881eca21 <unknown>\n#10 0x55b88840418e <unknown>\n#11 0x55b888407622 <unknown>\n#12 0x55b8883eaaae <unknown>\n#13 0x55b8884082a3 <unknown>\n#14 0x55b8883deecf <unknown>\n#15 0x55b888428588 <unknown>\n#16 0x55b888428706 <unknown>\n#17 0x55b8884428b2 <unknown>\n#18 0x7ff9e8e8f609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","time":{"start":1667413847209,"stop":1667413857582,"duration":10373}},{"uid":"fd4ac7d4e7aa535e","reportUrl":"https://timjden.github.io/cinc_assignment/26//#testresult/fd4ac7d4e7aa535e","status":"failed","statusDetails":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5646a5dba2c3 <unknown>\n#1 0x5646a5bc383a <unknown>\n#2 0x5646a5bfc985 <unknown>\n#3 0x5646a5bfcb61 <unknown>\n#4 0x5646a5c34d14 <unknown>\n#5 0x5646a5c1af6d <unknown>\n#6 0x5646a5c32a50 <unknown>\n#7 0x5646a5c1ad63 <unknown>\n#8 0x5646a5bef7e3 <unknown>\n#9 0x5646a5bf0a21 <unknown>\n#10 0x5646a5e0818e <unknown>\n#11 0x5646a5e0b622 <unknown>\n#12 0x5646a5deeaae <unknown>\n#13 0x5646a5e0c2a3 <unknown>\n#14 0x5646a5de2ecf <unknown>\n#15 0x5646a5e2c588 <unknown>\n#16 0x5646a5e2c706 <unknown>\n#17 0x5646a5e468b2 <unknown>\n#18 0x7f9c4df18609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x5646a5dba2c3 <unknown>\n#1 0x5646a5bc383a <unknown>\n#2 0x5646a5bfc985 <unknown>\n#3 0x5646a5bfcb61 <unknown>\n#4 0x5646a5c34d14 <unknown>\n#5 0x5646a5c1af6d <unknown>\n#6 0x5646a5c32a50 <unknown>\n#7 0x5646a5c1ad63 <unknown>\n#8 0x5646a5bef7e3 <unknown>\n#9 0x5646a5bf0a21 <unknown>\n#10 0x5646a5e0818e <unknown>\n#11 0x5646a5e0b622 <unknown>\n#12 0x5646a5deeaae <unknown>\n#13 0x5646a5e0c2a3 <unknown>\n#14 0x5646a5de2ecf <unknown>\n#15 0x5646a5e2c588 <unknown>\n#16 0x5646a5e2c706 <unknown>\n#17 0x5646a5e468b2 <unknown>\n#18 0x7f9c4df18609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","time":{"start":1667413661907,"stop":1667413672249,"duration":10342}},{"uid":"cb6b6841bec744cc","reportUrl":"https://timjden.github.io/cinc_assignment/25//#testresult/cb6b6841bec744cc","status":"passed","time":{"start":1667413413324,"stop":1667413430917,"duration":17593}},{"uid":"90bd9f2d78c5f1ac","reportUrl":"https://timjden.github.io/cinc_assignment/24//#testresult/90bd9f2d78c5f1ac","status":"passed","time":{"start":1667412771914,"stop":1667412789538,"duration":17624}},{"uid":"532c3c2e9bcedda9","reportUrl":"https://timjden.github.io/cinc_assignment/23//#testresult/532c3c2e9bcedda9","status":"failed","statusDetails":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5566378172c3 <unknown>\n#1 0x55663762083a <unknown>\n#2 0x556637659985 <unknown>\n#3 0x556637659b61 <unknown>\n#4 0x556637691d14 <unknown>\n#5 0x556637677f6d <unknown>\n#6 0x55663768fa50 <unknown>\n#7 0x556637677d63 <unknown>\n#8 0x55663764c7e3 <unknown>\n#9 0x55663764da21 <unknown>\n#10 0x55663786518e <unknown>\n#11 0x556637868622 <unknown>\n#12 0x55663784baae <unknown>\n#13 0x5566378692a3 <unknown>\n#14 0x55663783fecf <unknown>\n#15 0x556637889588 <unknown>\n#16 0x556637889706 <unknown>\n#17 0x5566378a38b2 <unknown>\n#18 0x7f93c8083609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x5566378172c3 <unknown>\n#1 0x55663762083a <unknown>\n#2 0x556637659985 <unknown>\n#3 0x556637659b61 <unknown>\n#4 0x556637691d14 <unknown>\n#5 0x556637677f6d <unknown>\n#6 0x55663768fa50 <unknown>\n#7 0x556637677d63 <unknown>\n#8 0x55663764c7e3 <unknown>\n#9 0x55663764da21 <unknown>\n#10 0x55663786518e <unknown>\n#11 0x556637868622 <unknown>\n#12 0x55663784baae <unknown>\n#13 0x5566378692a3 <unknown>\n#14 0x55663783fecf <unknown>\n#15 0x556637889588 <unknown>\n#16 0x556637889706 <unknown>\n#17 0x5566378a38b2 <unknown>\n#18 0x7f93c8083609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","time":{"start":1667412548599,"stop":1667412558911,"duration":10312}}]},"tags":[]},"source":"fa2c1d05d11af288.json","parameterValues":["uhqom-duqmum-tepXe7","Test Collection","technical_assignment"]}