{"uid":"532c3c2e9bcedda9","name":"Add a Recipe to a Collection -- @1.1 ","fullName":"Collections: Add a Recipe to a Collection","historyId":"064f3a57ed0026516ddf41142463fedd","time":{"start":1667412548599,"stop":1667412558911,"duration":10312},"status":"failed","statusMessage":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5566378172c3 <unknown>\n#1 0x55663762083a <unknown>\n#2 0x556637659985 <unknown>\n#3 0x556637659b61 <unknown>\n#4 0x556637691d14 <unknown>\n#5 0x556637677f6d <unknown>\n#6 0x55663768fa50 <unknown>\n#7 0x556637677d63 <unknown>\n#8 0x55663764c7e3 <unknown>\n#9 0x55663764da21 <unknown>\n#10 0x55663786518e <unknown>\n#11 0x556637868622 <unknown>\n#12 0x55663784baae <unknown>\n#13 0x5566378692a3 <unknown>\n#14 0x55663783fecf <unknown>\n#15 0x556637889588 <unknown>\n#16 0x556637889706 <unknown>\n#17 0x5566378a38b2 <unknown>\n#18 0x7f93c8083609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x5566378172c3 <unknown>\n#1 0x55663762083a <unknown>\n#2 0x556637659985 <unknown>\n#3 0x556637659b61 <unknown>\n#4 0x556637691d14 <unknown>\n#5 0x556637677f6d <unknown>\n#6 0x55663768fa50 <unknown>\n#7 0x556637677d63 <unknown>\n#8 0x55663764c7e3 <unknown>\n#9 0x55663764da21 <unknown>\n#10 0x55663786518e <unknown>\n#11 0x556637868622 <unknown>\n#12 0x55663784baae <unknown>\n#13 0x5566378692a3 <unknown>\n#14 0x55663783fecf <unknown>\n#15 0x556637889588 <unknown>\n#16 0x556637889706 <unknown>\n#17 0x5566378a38b2 <unknown>\n#18 0x7f93c8083609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","statusTrace":"  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/collection_steps.py\", line 19, in step_impl\n    context.execute_steps(f\"\"\"\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/runner.py\", line 404, in execute_steps\n    assert False, message\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5566378172c3 <unknown>\n#1 0x55663762083a <unknown>\n#2 0x556637659985 <unknown>\n#3 0x556637659b61 <unknown>\n#4 0x556637691d14 <unknown>\n#5 0x556637677f6d <unknown>\n#6 0x55663768fa50 <unknown>\n#7 0x556637677d63 <unknown>\n#8 0x55663764c7e3 <unknown>\n#9 0x55663764da21 <unknown>\n#10 0x55663786518e <unknown>\n#11 0x556637868622 <unknown>\n#12 0x55663784baae <unknown>\n#13 0x5566378692a3 <unknown>\n#14 0x55663783fecf <unknown>\n#15 0x556637889588 <unknown>\n#16 0x556637889706 <unknown>\n#17 0x5566378a38b2 <unknown>\n#18 0x7f93c8083609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x5566378172c3 <unknown>\n#1 0x55663762083a <unknown>\n#2 0x556637659985 <unknown>\n#3 0x556637659b61 <unknown>\n#4 0x556637691d14 <unknown>\n#5 0x556637677f6d <unknown>\n#6 0x55663768fa50 <unknown>\n#7 0x556637677d63 <unknown>\n#8 0x55663764c7e3 <unknown>\n#9 0x55663764da21 <unknown>\n#10 0x55663786518e <unknown>\n#11 0x556637868622 <unknown>\n#12 0x55663784baae <unknown>\n#13 0x5566378692a3 <unknown>\n#14 0x55663783fecf <unknown>\n#15 0x556637889588 <unknown>\n#16 0x556637889706 <unknown>\n#17 0x5566378a38b2 <unknown>\n#18 0x7f93c8083609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","statusTrace":"  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/collection_steps.py\", line 19, in step_impl\n    context.execute_steps(f\"\"\"\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/runner.py\", line 404, in execute_steps\n    assert False, message\n","steps":[{"name":"Given User is logged in as username: technical_assignment, password: uhqom-duqmum-tepXe7","time":{"start":1667412548599,"stop":1667412558910,"duration":10311},"status":"failed","statusMessage":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5566378172c3 <unknown>\n#1 0x55663762083a <unknown>\n#2 0x556637659985 <unknown>\n#3 0x556637659b61 <unknown>\n#4 0x556637691d14 <unknown>\n#5 0x556637677f6d <unknown>\n#6 0x55663768fa50 <unknown>\n#7 0x556637677d63 <unknown>\n#8 0x55663764c7e3 <unknown>\n#9 0x55663764da21 <unknown>\n#10 0x55663786518e <unknown>\n#11 0x556637868622 <unknown>\n#12 0x55663784baae <unknown>\n#13 0x5566378692a3 <unknown>\n#14 0x55663783fecf <unknown>\n#15 0x556637889588 <unknown>\n#16 0x556637889706 <unknown>\n#17 0x5566378a38b2 <unknown>\n#18 0x7f93c8083609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x5566378172c3 <unknown>\n#1 0x55663762083a <unknown>\n#2 0x556637659985 <unknown>\n#3 0x556637659b61 <unknown>\n#4 0x556637691d14 <unknown>\n#5 0x556637677f6d <unknown>\n#6 0x55663768fa50 <unknown>\n#7 0x556637677d63 <unknown>\n#8 0x55663764c7e3 <unknown>\n#9 0x55663764da21 <unknown>\n#10 0x55663786518e <unknown>\n#11 0x556637868622 <unknown>\n#12 0x55663784baae <unknown>\n#13 0x5566378692a3 <unknown>\n#14 0x55663783fecf <unknown>\n#15 0x556637889588 <unknown>\n#16 0x556637889706 <unknown>\n#17 0x5566378a38b2 <unknown>\n#18 0x7f93c8083609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","statusTrace":"  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/collection_steps.py\", line 19, in step_impl\n    context.execute_steps(f\"\"\"\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/runner.py\", line 404, in execute_steps\n    assert False, message\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true},{"name":"Given A Collection with title: Test Collection, exists","time":{"start":1667412558911,"stop":1667412558911,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Given User is on the Dashboard page","time":{"start":1667412558911,"stop":1667412558911,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks Explore","time":{"start":1667412558911,"stop":1667412558911,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks a Recipe","time":{"start":1667412558911,"stop":1667412558911,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks kebab icon","time":{"start":1667412558911,"stop":1667412558911,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User hovers on Add to collection","time":{"start":1667412558911,"stop":1667412558911,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Then Collection with title: Test Collection, is present","time":{"start":1667412558911,"stop":1667412558911,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks title: Test Collection","time":{"start":1667412558911,"stop":1667412558911,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks profile icon","time":{"start":1667412558911,"stop":1667412558911,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks Dashboard","time":{"start":1667412558911,"stop":1667412558911,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks Collections tab","time":{"start":1667412558911,"stop":1667412558911,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Then Recipe is visible in Collection","time":{"start":1667412558911,"stop":1667412558911,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Then Delete the Collection","time":{"start":1667412558911,"stop":1667412558911,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"attachments":[],"parameters":[],"stepsCount":14,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"Collections"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"password","value":"uhqom-duqmum-tepXe7"},{"name":"title","value":"Test Collection"},{"name":"username","value":"technical_assignment"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"532c3c2e9bcedda9.json","parameterValues":["uhqom-duqmum-tepXe7","Test Collection","technical_assignment"]}