{"uid":"ff19ead8aeb7d483","name":"Recipe adjustment -- @1.1 ","fullName":"Recipe: Recipe adjustment","historyId":"1d6b567ca8de43430431a32431c65783","time":{"start":1667421170236,"stop":1667421180586,"duration":10350},"status":"failed","statusMessage":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 17, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55af806102c3 <unknown>\n#1 0x55af8041983a <unknown>\n#2 0x55af80452985 <unknown>\n#3 0x55af80452b61 <unknown>\n#4 0x55af8048ad14 <unknown>\n#5 0x55af80470f6d <unknown>\n#6 0x55af80488a50 <unknown>\n#7 0x55af80470d63 <unknown>\n#8 0x55af804457e3 <unknown>\n#9 0x55af80446a21 <unknown>\n#10 0x55af8065e18e <unknown>\n#11 0x55af80661622 <unknown>\n#12 0x55af80644aae <unknown>\n#13 0x55af806622a3 <unknown>\n#14 0x55af80638ecf <unknown>\n#15 0x55af80682588 <unknown>\n#16 0x55af80682706 <unknown>\n#17 0x55af8069c8b2 <unknown>\n#18 0x7fcabf406609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 26, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x55af806102c3 <unknown>\n#1 0x55af8041983a <unknown>\n#2 0x55af80452985 <unknown>\n#3 0x55af80452b61 <unknown>\n#4 0x55af8048ad14 <unknown>\n#5 0x55af80470f6d <unknown>\n#6 0x55af80488a50 <unknown>\n#7 0x55af80470d63 <unknown>\n#8 0x55af804457e3 <unknown>\n#9 0x55af80446a21 <unknown>\n#10 0x55af8065e18e <unknown>\n#11 0x55af80661622 <unknown>\n#12 0x55af80644aae <unknown>\n#13 0x55af806622a3 <unknown>\n#14 0x55af80638ecf <unknown>\n#15 0x55af80682588 <unknown>\n#16 0x55af80682706 <unknown>\n#17 0x55af8069c8b2 <unknown>\n#18 0x7fcabf406609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 26, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","statusTrace":"  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/collection_steps.py\", line 19, in step_impl\n    context.execute_steps(f\"\"\"\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/runner.py\", line 404, in execute_steps\n    assert False, message\n","flaky":true,"newFailed":true,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 17, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55af806102c3 <unknown>\n#1 0x55af8041983a <unknown>\n#2 0x55af80452985 <unknown>\n#3 0x55af80452b61 <unknown>\n#4 0x55af8048ad14 <unknown>\n#5 0x55af80470f6d <unknown>\n#6 0x55af80488a50 <unknown>\n#7 0x55af80470d63 <unknown>\n#8 0x55af804457e3 <unknown>\n#9 0x55af80446a21 <unknown>\n#10 0x55af8065e18e <unknown>\n#11 0x55af80661622 <unknown>\n#12 0x55af80644aae <unknown>\n#13 0x55af806622a3 <unknown>\n#14 0x55af80638ecf <unknown>\n#15 0x55af80682588 <unknown>\n#16 0x55af80682706 <unknown>\n#17 0x55af8069c8b2 <unknown>\n#18 0x7fcabf406609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 26, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x55af806102c3 <unknown>\n#1 0x55af8041983a <unknown>\n#2 0x55af80452985 <unknown>\n#3 0x55af80452b61 <unknown>\n#4 0x55af8048ad14 <unknown>\n#5 0x55af80470f6d <unknown>\n#6 0x55af80488a50 <unknown>\n#7 0x55af80470d63 <unknown>\n#8 0x55af804457e3 <unknown>\n#9 0x55af80446a21 <unknown>\n#10 0x55af8065e18e <unknown>\n#11 0x55af80661622 <unknown>\n#12 0x55af80644aae <unknown>\n#13 0x55af806622a3 <unknown>\n#14 0x55af80638ecf <unknown>\n#15 0x55af80682588 <unknown>\n#16 0x55af80682706 <unknown>\n#17 0x55af8069c8b2 <unknown>\n#18 0x7fcabf406609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 26, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","statusTrace":"  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/collection_steps.py\", line 19, in step_impl\n    context.execute_steps(f\"\"\"\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/runner.py\", line 404, in execute_steps\n    assert False, message\n","steps":[{"name":"Given User is logged in as username: technical_assignment, password: uhqom-duqmum-tepXe7","time":{"start":1667421170236,"stop":1667421180585,"duration":10349},"status":"failed","statusMessage":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 17, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55af806102c3 <unknown>\n#1 0x55af8041983a <unknown>\n#2 0x55af80452985 <unknown>\n#3 0x55af80452b61 <unknown>\n#4 0x55af8048ad14 <unknown>\n#5 0x55af80470f6d <unknown>\n#6 0x55af80488a50 <unknown>\n#7 0x55af80470d63 <unknown>\n#8 0x55af804457e3 <unknown>\n#9 0x55af80446a21 <unknown>\n#10 0x55af8065e18e <unknown>\n#11 0x55af80661622 <unknown>\n#12 0x55af80644aae <unknown>\n#13 0x55af806622a3 <unknown>\n#14 0x55af80638ecf <unknown>\n#15 0x55af80682588 <unknown>\n#16 0x55af80682706 <unknown>\n#17 0x55af8069c8b2 <unknown>\n#18 0x7fcabf406609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 26, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x55af806102c3 <unknown>\n#1 0x55af8041983a <unknown>\n#2 0x55af80452985 <unknown>\n#3 0x55af80452b61 <unknown>\n#4 0x55af8048ad14 <unknown>\n#5 0x55af80470f6d <unknown>\n#6 0x55af80488a50 <unknown>\n#7 0x55af80470d63 <unknown>\n#8 0x55af804457e3 <unknown>\n#9 0x55af80446a21 <unknown>\n#10 0x55af8065e18e <unknown>\n#11 0x55af80661622 <unknown>\n#12 0x55af80644aae <unknown>\n#13 0x55af806622a3 <unknown>\n#14 0x55af80638ecf <unknown>\n#15 0x55af80682588 <unknown>\n#16 0x55af80682706 <unknown>\n#17 0x55af8069c8b2 <unknown>\n#18 0x7fcabf406609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 26, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","statusTrace":"  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/collection_steps.py\", line 19, in step_impl\n    context.execute_steps(f\"\"\"\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/runner.py\", line 404, in execute_steps\n    assert False, message\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true},{"name":"When User clicks Explore","time":{"start":1667421180586,"stop":1667421180586,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks a Recipe","time":{"start":1667421180586,"stop":1667421180586,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks adjustment icon","time":{"start":1667421180586,"stop":1667421180586,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User hovers on Units","time":{"start":1667421180586,"stop":1667421180586,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks Metric","time":{"start":1667421180586,"stop":1667421180586,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User clicks adjustment icon","time":{"start":1667421180586,"stop":1667421180586,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User hovers on Scale","time":{"start":1667421180586,"stop":1667421180586,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User scales recipe X2","time":{"start":1667421180586,"stop":1667421180586,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Then Recipe amounts have been correctly scaled","time":{"start":1667421180586,"stop":1667421180586,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"attachments":[],"parameters":[],"stepsCount":10,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"Recipe"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"password","value":"uhqom-duqmum-tepXe7"},{"name":"username","value":"technical_assignment"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":2,"broken":0,"skipped":0,"passed":7,"unknown":0,"total":9},"items":[{"uid":"134edf7673071e83","reportUrl":"https://timjden.github.io/cinc_assignment/38//#testresult/134edf7673071e83","status":"passed","time":{"start":1667421087155,"stop":1667421108396,"duration":21241}},{"uid":"ad554ca6e236cfc1","reportUrl":"https://timjden.github.io/cinc_assignment/37//#testresult/ad554ca6e236cfc1","status":"passed","time":{"start":1667420830128,"stop":1667420851733,"duration":21605}},{"uid":"1435335c3673e417","reportUrl":"https://timjden.github.io/cinc_assignment/37//#testresult/1435335c3673e417","status":"passed","time":{"start":1667420489903,"stop":1667420510748,"duration":20845}},{"uid":"b2fb9cdeabb676fa","reportUrl":"https://timjden.github.io/cinc_assignment/36//#testresult/b2fb9cdeabb676fa","status":"passed","time":{"start":1667420253067,"stop":1667420273441,"duration":20374}},{"uid":"f96c96d8518735f1","reportUrl":"https://timjden.github.io/cinc_assignment/36//#testresult/f96c96d8518735f1","status":"failed","statusDetails":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 17, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x558be34c7463 <unknown>\n#1 0x558be328b8d8 <unknown>\n#2 0x558be32c943a <unknown>\n#3 0x558be32c9651 <unknown>\n#4 0x558be33057a4 <unknown>\n#5 0x558be32ea64d <unknown>\n#6 0x558be330330f <unknown>\n#7 0x558be32ea443 <unknown>\n#8 0x558be32bb3c5 <unknown>\n#9 0x558be32bc531 <unknown>\n#10 0x558be3519dce <unknown>\n#11 0x558be351d192 <unknown>\n#12 0x558be34fe93e <unknown>\n#13 0x558be351e103 <unknown>\n#14 0x558be34f1d85 <unknown>\n#15 0x558be353f0a8 <unknown>\n#16 0x558be353f239 <unknown>\n#17 0x558be355a492 <unknown>\n#18 0x7f7cb393f609 start_thread\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 26, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=107.0.5304.87)\nStacktrace:\n#0 0x558be34c7463 <unknown>\n#1 0x558be328b8d8 <unknown>\n#2 0x558be32c943a <unknown>\n#3 0x558be32c9651 <unknown>\n#4 0x558be33057a4 <unknown>\n#5 0x558be32ea64d <unknown>\n#6 0x558be330330f <unknown>\n#7 0x558be32ea443 <unknown>\n#8 0x558be32bb3c5 <unknown>\n#9 0x558be32bc531 <unknown>\n#10 0x558be3519dce <unknown>\n#11 0x558be351d192 <unknown>\n#12 0x558be34fe93e <unknown>\n#13 0x558be351e103 <unknown>\n#14 0x558be34f1d85 <unknown>\n#15 0x558be353f0a8 <unknown>\n#16 0x558be353f239 <unknown>\n#17 0x558be355a492 <unknown>\n#18 0x7f7cb393f609 start_thread\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 26, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","time":{"start":1667419976791,"stop":1667419987175,"duration":10384}},{"uid":"641277f970e1d453","reportUrl":"https://timjden.github.io/cinc_assignment/35//#testresult/641277f970e1d453","status":"passed","time":{"start":1667418324850,"stop":1667418343549,"duration":18699}},{"uid":"88c66963367957a1","reportUrl":"https://timjden.github.io/cinc_assignment/34//#testresult/88c66963367957a1","status":"passed","time":{"start":1667418007852,"stop":1667418026630,"duration":18778}},{"uid":"7ab9eb386e4a3332","reportUrl":"https://timjden.github.io/cinc_assignment/33//#testresult/7ab9eb386e4a3332","status":"passed","time":{"start":1667417535720,"stop":1667417553909,"duration":18189}}]},"tags":[]},"source":"ff19ead8aeb7d483.json","parameterValues":["uhqom-duqmum-tepXe7","technical_assignment"]}