{"1d6b567ca8de43430431a32431c65783":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"7ab9eb386e4a3332","reportUrl":"https://timjden.github.io/cinc_assignment/33//#testresult/7ab9eb386e4a3332","status":"passed","time":{"start":1667417535720,"stop":1667417553909,"duration":18189}}]},"f6a5c6c7991a80969fdbcfb3958349c2":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":11,"unknown":0,"total":12},"items":[{"uid":"cd9394e1581c8676","reportUrl":"https://timjden.github.io/cinc_assignment/33//#testresult/cd9394e1581c8676","status":"passed","time":{"start":1667417491007,"stop":1667417494168,"duration":3161}},{"uid":"452be6c8b5f9bdcf","reportUrl":"https://timjden.github.io/cinc_assignment/32//#testresult/452be6c8b5f9bdcf","status":"passed","time":{"start":1667414642803,"stop":1667414647582,"duration":4779}},{"uid":"9aa2d066533202c1","reportUrl":"https://timjden.github.io/cinc_assignment/31//#testresult/9aa2d066533202c1","status":"passed","time":{"start":1667414580495,"stop":1667414585983,"duration":5488}},{"uid":"b530071ca25d3a52","reportUrl":"https://timjden.github.io/cinc_assignment/30//#testresult/b530071ca25d3a52","status":"passed","time":{"start":1667414321279,"stop":1667414325088,"duration":3809}},{"uid":"e91f81459e4429d2","reportUrl":"https://timjden.github.io/cinc_assignment/29//#testresult/e91f81459e4429d2","status":"passed","time":{"start":1667414191875,"stop":1667414195761,"duration":3886}},{"uid":"a963f3687ac0b49c","reportUrl":"https://timjden.github.io/cinc_assignment/28//#testresult/a963f3687ac0b49c","status":"passed","time":{"start":1667414129308,"stop":1667414132982,"duration":3674}},{"uid":"ce414307ba8475d9","reportUrl":"https://timjden.github.io/cinc_assignment/28//#testresult/ce414307ba8475d9","status":"passed","time":{"start":1667413993959,"stop":1667413998611,"duration":4652}},{"uid":"f4e8b34808965f7","reportUrl":"https://timjden.github.io/cinc_assignment/27//#testresult/f4e8b34808965f7","status":"passed","time":{"start":1667413842199,"stop":1667413847208,"duration":5009}},{"uid":"d31ba3263e8913d0","reportUrl":"https://timjden.github.io/cinc_assignment/26//#testresult/d31ba3263e8913d0","status":"passed","time":{"start":1667413656874,"stop":1667413661907,"duration":5033}},{"uid":"fc561c39e3b1b4e4","reportUrl":"https://timjden.github.io/cinc_assignment/25//#testresult/fc561c39e3b1b4e4","status":"passed","time":{"start":1667413407999,"stop":1667413413324,"duration":5325}},{"uid":"13e6ea073fed87e7","reportUrl":"https://timjden.github.io/cinc_assignment/24//#testresult/13e6ea073fed87e7","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x555ce63ac2c3 <unknown>\n#1 0x555ce61b583a <unknown>\n#2 0x555ce61ee985 <unknown>\n#3 0x555ce61eeb61 <unknown>\n#4 0x555ce6226d14 <unknown>\n#5 0x555ce620cf6d <unknown>\n#6 0x555ce6224a50 <unknown>\n#7 0x555ce620cd63 <unknown>\n#8 0x555ce61e17e3 <unknown>\n#9 0x555ce61e2a21 <unknown>\n#10 0x555ce63fa18e <unknown>\n#11 0x555ce63fd622 <unknown>\n#12 0x555ce63e0aae <unknown>\n#13 0x555ce63fe2a3 <unknown>\n#14 0x555ce63d4ecf <unknown>\n#15 0x555ce641e588 <unknown>\n#16 0x555ce641e706 <unknown>\n#17 0x555ce64388b2 <unknown>\n#18 0x7fb34a4dc609 <unknown>\n\n","time":{"start":1667412758108,"stop":1667412771913,"duration":13805}},{"uid":"1def942ab23243ef","reportUrl":"https://timjden.github.io/cinc_assignment/23//#testresult/1def942ab23243ef","status":"passed","time":{"start":1667412543528,"stop":1667412548598,"duration":5070}}]},"a34d535ff7756f44d3753d91bfe6b623":{"statistic":{"failed":12,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":12},"items":[{"uid":"b73897d47932e320","reportUrl":"https://timjden.github.io/cinc_assignment/33//#testresult/b73897d47932e320","status":"failed","statusDetails":"AssertionError\n","time":{"start":1667417510841,"stop":1667417523721,"duration":12880}},{"uid":"b6c9c4d2d5de36fe","reportUrl":"https://timjden.github.io/cinc_assignment/32//#testresult/b6c9c4d2d5de36fe","status":"failed","statusDetails":"AssertionError\n","time":{"start":1667414664028,"stop":1667414676944,"duration":12916}},{"uid":"7b881886dc96b54d","reportUrl":"https://timjden.github.io/cinc_assignment/31//#testresult/7b881886dc96b54d","status":"failed","statusDetails":"AssertionError\n","time":{"start":1667414596390,"stop":1667414608984,"duration":12594}},{"uid":"eff9a169f67dd42e","reportUrl":"https://timjden.github.io/cinc_assignment/30//#testresult/eff9a169f67dd42e","status":"failed","statusDetails":"AssertionError\n","time":{"start":1667414335418,"stop":1667414348050,"duration":12632}},{"uid":"a0d603ea795c3327","reportUrl":"https://timjden.github.io/cinc_assignment/29//#testresult/a0d603ea795c3327","status":"failed","statusDetails":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55feffd8e2c3 <unknown>\n#1 0x55feffb9783a <unknown>\n#2 0x55feffbd0985 <unknown>\n#3 0x55feffbd0b61 <unknown>\n#4 0x55feffc08d14 <unknown>\n#5 0x55feffbeef6d <unknown>\n#6 0x55feffc06a50 <unknown>\n#7 0x55feffbeed63 <unknown>\n#8 0x55feffbc37e3 <unknown>\n#9 0x55feffbc4a21 <unknown>\n#10 0x55feffddc18e <unknown>\n#11 0x55feffddf622 <unknown>\n#12 0x55feffdc2aae <unknown>\n#13 0x55feffde02a3 <unknown>\n#14 0x55feffdb6ecf <unknown>\n#15 0x55feffe00588 <unknown>\n#16 0x55feffe00706 <unknown>\n#17 0x55feffe1a8b2 <unknown>\n#18 0x7fc3efce6609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x55feffd8e2c3 <unknown>\n#1 0x55feffb9783a <unknown>\n#2 0x55feffbd0985 <unknown>\n#3 0x55feffbd0b61 <unknown>\n#4 0x55feffc08d14 <unknown>\n#5 0x55feffbeef6d <unknown>\n#6 0x55feffc06a50 <unknown>\n#7 0x55feffbeed63 <unknown>\n#8 0x55feffbc37e3 <unknown>\n#9 0x55feffbc4a21 <unknown>\n#10 0x55feffddc18e <unknown>\n#11 0x55feffddf622 <unknown>\n#12 0x55feffdc2aae <unknown>\n#13 0x55feffde02a3 <unknown>\n#14 0x55feffdb6ecf <unknown>\n#15 0x55feffe00588 <unknown>\n#16 0x55feffe00706 <unknown>\n#17 0x55feffe1a8b2 <unknown>\n#18 0x7fc3efce6609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","time":{"start":1667414212348,"stop":1667414222731,"duration":10383}},{"uid":"cb8db3b7734f7ee5","reportUrl":"https://timjden.github.io/cinc_assignment/28//#testresult/cb8db3b7734f7ee5","status":"failed","statusDetails":"AssertionError\n","time":{"start":1667414143408,"stop":1667414157357,"duration":13949}},{"uid":"90a326291408e03","reportUrl":"https://timjden.github.io/cinc_assignment/28//#testresult/90a326291408e03","status":"failed","statusDetails":"AssertionError\n","time":{"start":1667414015812,"stop":1667414029204,"duration":13392}},{"uid":"321233665647f3c9","reportUrl":"https://timjden.github.io/cinc_assignment/27//#testresult/321233665647f3c9","status":"failed","statusDetails":"AssertionError\n","time":{"start":1667413857582,"stop":1667413870840,"duration":13258}},{"uid":"66ae1c379c2a0fa0","reportUrl":"https://timjden.github.io/cinc_assignment/26//#testresult/66ae1c379c2a0fa0","status":"failed","statusDetails":"AssertionError\n","time":{"start":1667413672250,"stop":1667413686391,"duration":14141}},{"uid":"357cb1795d771f83","reportUrl":"https://timjden.github.io/cinc_assignment/25//#testresult/357cb1795d771f83","status":"failed","statusDetails":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55e01270a2c3 <unknown>\n#1 0x55e01251383a <unknown>\n#2 0x55e01254c985 <unknown>\n#3 0x55e01254cb61 <unknown>\n#4 0x55e012584d14 <unknown>\n#5 0x55e01256af6d <unknown>\n#6 0x55e012582a50 <unknown>\n#7 0x55e01256ad63 <unknown>\n#8 0x55e01253f7e3 <unknown>\n#9 0x55e012540a21 <unknown>\n#10 0x55e01275818e <unknown>\n#11 0x55e01275b622 <unknown>\n#12 0x55e01273eaae <unknown>\n#13 0x55e01275c2a3 <unknown>\n#14 0x55e012732ecf <unknown>\n#15 0x55e01277c588 <unknown>\n#16 0x55e01277c706 <unknown>\n#17 0x55e0127968b2 <unknown>\n#18 0x7f07ef7f3609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x55e01270a2c3 <unknown>\n#1 0x55e01251383a <unknown>\n#2 0x55e01254c985 <unknown>\n#3 0x55e01254cb61 <unknown>\n#4 0x55e012584d14 <unknown>\n#5 0x55e01256af6d <unknown>\n#6 0x55e012582a50 <unknown>\n#7 0x55e01256ad63 <unknown>\n#8 0x55e01253f7e3 <unknown>\n#9 0x55e012540a21 <unknown>\n#10 0x55e01275818e <unknown>\n#11 0x55e01275b622 <unknown>\n#12 0x55e01273eaae <unknown>\n#13 0x55e01275c2a3 <unknown>\n#14 0x55e012732ecf <unknown>\n#15 0x55e01277c588 <unknown>\n#16 0x55e01277c706 <unknown>\n#17 0x55e0127968b2 <unknown>\n#18 0x7f07ef7f3609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","time":{"start":1667413430917,"stop":1667413441282,"duration":10365}},{"uid":"747c1648444e509e","reportUrl":"https://timjden.github.io/cinc_assignment/24//#testresult/747c1648444e509e","status":"failed","statusDetails":"AssertionError\n","time":{"start":1667412789539,"stop":1667412802782,"duration":13243}},{"uid":"d9d6c18078018573","reportUrl":"https://timjden.github.io/cinc_assignment/23//#testresult/d9d6c18078018573","status":"failed","statusDetails":"AssertionError\n","time":{"start":1667412558912,"stop":1667412572022,"duration":13110}}]},"008ee9d2b6280a68e13bf0acd583d8ff":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":8,"unknown":0,"total":12},"items":[{"uid":"f5cd7404533e4c3b","reportUrl":"https://timjden.github.io/cinc_assignment/33//#testresult/f5cd7404533e4c3b","status":"passed","time":{"start":1667417523723,"stop":1667417535718,"duration":11995}},{"uid":"10905c723a146cfd","reportUrl":"https://timjden.github.io/cinc_assignment/32//#testresult/10905c723a146cfd","status":"passed","time":{"start":1667414676946,"stop":1667414688448,"duration":11502}},{"uid":"d77c47aa8d0a89af","reportUrl":"https://timjden.github.io/cinc_assignment/31//#testresult/d77c47aa8d0a89af","status":"passed","time":{"start":1667414608985,"stop":1667414620648,"duration":11663}},{"uid":"c97d45a876e6a6cf","reportUrl":"https://timjden.github.io/cinc_assignment/30//#testresult/c97d45a876e6a6cf","status":"passed","time":{"start":1667414348051,"stop":1667414359345,"duration":11294}},{"uid":"18296a37ee795091","reportUrl":"https://timjden.github.io/cinc_assignment/29//#testresult/18296a37ee795091","status":"passed","time":{"start":1667414222732,"stop":1667414234779,"duration":12047}},{"uid":"993cc93fcb5e4d1a","reportUrl":"https://timjden.github.io/cinc_assignment/28//#testresult/993cc93fcb5e4d1a","status":"passed","time":{"start":1667414157359,"stop":1667414169450,"duration":12091}},{"uid":"874dccdc73838559","reportUrl":"https://timjden.github.io/cinc_assignment/28//#testresult/874dccdc73838559","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x55756d6b42c3 <unknown>\n#1 0x55756d4bd83a <unknown>\n#2 0x55756d4f6985 <unknown>\n#3 0x55756d4f6b61 <unknown>\n#4 0x55756d52ed14 <unknown>\n#5 0x55756d514f6d <unknown>\n#6 0x55756d52ca50 <unknown>\n#7 0x55756d514d63 <unknown>\n#8 0x55756d4e97e3 <unknown>\n#9 0x55756d4eaa21 <unknown>\n#10 0x55756d70218e <unknown>\n#11 0x55756d705622 <unknown>\n#12 0x55756d6e8aae <unknown>\n#13 0x55756d7062a3 <unknown>\n#14 0x55756d6dcecf <unknown>\n#15 0x55756d726588 <unknown>\n#16 0x55756d726706 <unknown>\n#17 0x55756d7408b2 <unknown>\n#18 0x7fa46ceb2609 <unknown>\n\n","time":{"start":1667414029205,"stop":1667414039575,"duration":10370}},{"uid":"7e2a8941240c9106","reportUrl":"https://timjden.github.io/cinc_assignment/27//#testresult/7e2a8941240c9106","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x55b8883b62c3 <unknown>\n#1 0x55b8881bf83a <unknown>\n#2 0x55b8881f8985 <unknown>\n#3 0x55b8881f8b61 <unknown>\n#4 0x55b888230d14 <unknown>\n#5 0x55b888216f6d <unknown>\n#6 0x55b88822ea50 <unknown>\n#7 0x55b888216d63 <unknown>\n#8 0x55b8881eb7e3 <unknown>\n#9 0x55b8881eca21 <unknown>\n#10 0x55b88840418e <unknown>\n#11 0x55b888407622 <unknown>\n#12 0x55b8883eaaae <unknown>\n#13 0x55b8884082a3 <unknown>\n#14 0x55b8883deecf <unknown>\n#15 0x55b888428588 <unknown>\n#16 0x55b888428706 <unknown>\n#17 0x55b8884428b2 <unknown>\n#18 0x7ff9e8e8f609 <unknown>\n\n","time":{"start":1667413870841,"stop":1667413881209,"duration":10368}},{"uid":"5630b56e0f040ceb","reportUrl":"https://timjden.github.io/cinc_assignment/26//#testresult/5630b56e0f040ceb","status":"passed","time":{"start":1667413686392,"stop":1667413698250,"duration":11858}},{"uid":"f56198b213f587ab","reportUrl":"https://timjden.github.io/cinc_assignment/25//#testresult/f56198b213f587ab","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x55e01270a2c3 <unknown>\n#1 0x55e01251383a <unknown>\n#2 0x55e01254c985 <unknown>\n#3 0x55e01254cb61 <unknown>\n#4 0x55e012584d14 <unknown>\n#5 0x55e01256af6d <unknown>\n#6 0x55e012582a50 <unknown>\n#7 0x55e01256ad63 <unknown>\n#8 0x55e01253f7e3 <unknown>\n#9 0x55e012540a21 <unknown>\n#10 0x55e01275818e <unknown>\n#11 0x55e01275b622 <unknown>\n#12 0x55e01273eaae <unknown>\n#13 0x55e01275c2a3 <unknown>\n#14 0x55e012732ecf <unknown>\n#15 0x55e01277c588 <unknown>\n#16 0x55e01277c706 <unknown>\n#17 0x55e0127968b2 <unknown>\n#18 0x7f07ef7f3609 <unknown>\n\n","time":{"start":1667413441283,"stop":1667413451625,"duration":10342}},{"uid":"4da4f61417065692","reportUrl":"https://timjden.github.io/cinc_assignment/24//#testresult/4da4f61417065692","status":"passed","time":{"start":1667412802784,"stop":1667412815768,"duration":12984}},{"uid":"69424292e49dee56","reportUrl":"https://timjden.github.io/cinc_assignment/23//#testresult/69424292e49dee56","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x5566378172c3 <unknown>\n#1 0x55663762083a <unknown>\n#2 0x556637659985 <unknown>\n#3 0x556637659b61 <unknown>\n#4 0x556637691d14 <unknown>\n#5 0x556637677f6d <unknown>\n#6 0x55663768fa50 <unknown>\n#7 0x556637677d63 <unknown>\n#8 0x55663764c7e3 <unknown>\n#9 0x55663764da21 <unknown>\n#10 0x55663786518e <unknown>\n#11 0x556637868622 <unknown>\n#12 0x55663784baae <unknown>\n#13 0x5566378692a3 <unknown>\n#14 0x55663783fecf <unknown>\n#15 0x556637889588 <unknown>\n#16 0x556637889706 <unknown>\n#17 0x5566378a38b2 <unknown>\n#18 0x7f93c8083609 <unknown>\n\n","time":{"start":1667412572023,"stop":1667412582321,"duration":10298}}]},"064f3a57ed0026516ddf41142463fedd":{"statistic":{"failed":6,"broken":0,"skipped":0,"passed":6,"unknown":0,"total":12},"items":[{"uid":"d05ef142e30d6e36","reportUrl":"https://timjden.github.io/cinc_assignment/33//#testresult/d05ef142e30d6e36","status":"passed","time":{"start":1667417494169,"stop":1667417510840,"duration":16671}},{"uid":"9be74d43082696b6","reportUrl":"https://timjden.github.io/cinc_assignment/32//#testresult/9be74d43082696b6","status":"passed","time":{"start":1667414647582,"stop":1667414664027,"duration":16445}},{"uid":"bb815d82163df7a","reportUrl":"https://timjden.github.io/cinc_assignment/31//#testresult/bb815d82163df7a","status":"failed","statusDetails":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5582c31432c3 <unknown>\n#1 0x5582c2f4c83a <unknown>\n#2 0x5582c2f85985 <unknown>\n#3 0x5582c2f85b61 <unknown>\n#4 0x5582c2fbdd14 <unknown>\n#5 0x5582c2fa3f6d <unknown>\n#6 0x5582c2fbba50 <unknown>\n#7 0x5582c2fa3d63 <unknown>\n#8 0x5582c2f787e3 <unknown>\n#9 0x5582c2f79a21 <unknown>\n#10 0x5582c319118e <unknown>\n#11 0x5582c3194622 <unknown>\n#12 0x5582c3177aae <unknown>\n#13 0x5582c31952a3 <unknown>\n#14 0x5582c316becf <unknown>\n#15 0x5582c31b5588 <unknown>\n#16 0x5582c31b5706 <unknown>\n#17 0x5582c31cf8b2 <unknown>\n#18 0x7fd57c78c609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x5582c31432c3 <unknown>\n#1 0x5582c2f4c83a <unknown>\n#2 0x5582c2f85985 <unknown>\n#3 0x5582c2f85b61 <unknown>\n#4 0x5582c2fbdd14 <unknown>\n#5 0x5582c2fa3f6d <unknown>\n#6 0x5582c2fbba50 <unknown>\n#7 0x5582c2fa3d63 <unknown>\n#8 0x5582c2f787e3 <unknown>\n#9 0x5582c2f79a21 <unknown>\n#10 0x5582c319118e <unknown>\n#11 0x5582c3194622 <unknown>\n#12 0x5582c3177aae <unknown>\n#13 0x5582c31952a3 <unknown>\n#14 0x5582c316becf <unknown>\n#15 0x5582c31b5588 <unknown>\n#16 0x5582c31b5706 <unknown>\n#17 0x5582c31cf8b2 <unknown>\n#18 0x7fd57c78c609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","time":{"start":1667414585984,"stop":1667414596389,"duration":10405}},{"uid":"8c7786825b5abc99","reportUrl":"https://timjden.github.io/cinc_assignment/30//#testresult/8c7786825b5abc99","status":"failed","statusDetails":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55ea828ce2c3 <unknown>\n#1 0x55ea826d783a <unknown>\n#2 0x55ea82710985 <unknown>\n#3 0x55ea82710b61 <unknown>\n#4 0x55ea82748d14 <unknown>\n#5 0x55ea8272ef6d <unknown>\n#6 0x55ea82746a50 <unknown>\n#7 0x55ea8272ed63 <unknown>\n#8 0x55ea827037e3 <unknown>\n#9 0x55ea82704a21 <unknown>\n#10 0x55ea8291c18e <unknown>\n#11 0x55ea8291f622 <unknown>\n#12 0x55ea82902aae <unknown>\n#13 0x55ea829202a3 <unknown>\n#14 0x55ea828f6ecf <unknown>\n#15 0x55ea82940588 <unknown>\n#16 0x55ea82940706 <unknown>\n#17 0x55ea8295a8b2 <unknown>\n#18 0x7efc2e136609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x55ea828ce2c3 <unknown>\n#1 0x55ea826d783a <unknown>\n#2 0x55ea82710985 <unknown>\n#3 0x55ea82710b61 <unknown>\n#4 0x55ea82748d14 <unknown>\n#5 0x55ea8272ef6d <unknown>\n#6 0x55ea82746a50 <unknown>\n#7 0x55ea8272ed63 <unknown>\n#8 0x55ea827037e3 <unknown>\n#9 0x55ea82704a21 <unknown>\n#10 0x55ea8291c18e <unknown>\n#11 0x55ea8291f622 <unknown>\n#12 0x55ea82902aae <unknown>\n#13 0x55ea829202a3 <unknown>\n#14 0x55ea828f6ecf <unknown>\n#15 0x55ea82940588 <unknown>\n#16 0x55ea82940706 <unknown>\n#17 0x55ea8295a8b2 <unknown>\n#18 0x7efc2e136609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","time":{"start":1667414325089,"stop":1667414335417,"duration":10328}},{"uid":"ff37c3602098201f","reportUrl":"https://timjden.github.io/cinc_assignment/29//#testresult/ff37c3602098201f","status":"passed","time":{"start":1667414195762,"stop":1667414212348,"duration":16586}},{"uid":"b075cf89d3fcea80","reportUrl":"https://timjden.github.io/cinc_assignment/28//#testresult/b075cf89d3fcea80","status":"failed","statusDetails":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5589550502c3 <unknown>\n#1 0x558954e5983a <unknown>\n#2 0x558954e92985 <unknown>\n#3 0x558954e92b61 <unknown>\n#4 0x558954ecad14 <unknown>\n#5 0x558954eb0f6d <unknown>\n#6 0x558954ec8a50 <unknown>\n#7 0x558954eb0d63 <unknown>\n#8 0x558954e857e3 <unknown>\n#9 0x558954e86a21 <unknown>\n#10 0x55895509e18e <unknown>\n#11 0x5589550a1622 <unknown>\n#12 0x558955084aae <unknown>\n#13 0x5589550a22a3 <unknown>\n#14 0x558955078ecf <unknown>\n#15 0x5589550c2588 <unknown>\n#16 0x5589550c2706 <unknown>\n#17 0x5589550dc8b2 <unknown>\n#18 0x7f49c14ce609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x5589550502c3 <unknown>\n#1 0x558954e5983a <unknown>\n#2 0x558954e92985 <unknown>\n#3 0x558954e92b61 <unknown>\n#4 0x558954ecad14 <unknown>\n#5 0x558954eb0f6d <unknown>\n#6 0x558954ec8a50 <unknown>\n#7 0x558954eb0d63 <unknown>\n#8 0x558954e857e3 <unknown>\n#9 0x558954e86a21 <unknown>\n#10 0x55895509e18e <unknown>\n#11 0x5589550a1622 <unknown>\n#12 0x558955084aae <unknown>\n#13 0x5589550a22a3 <unknown>\n#14 0x558955078ecf <unknown>\n#15 0x5589550c2588 <unknown>\n#16 0x5589550c2706 <unknown>\n#17 0x5589550dc8b2 <unknown>\n#18 0x7f49c14ce609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","time":{"start":1667414132983,"stop":1667414143407,"duration":10424}},{"uid":"fa2c1d05d11af288","reportUrl":"https://timjden.github.io/cinc_assignment/28//#testresult/fa2c1d05d11af288","status":"passed","time":{"start":1667413998612,"stop":1667414015811,"duration":17199}},{"uid":"8f5c565baa8038d8","reportUrl":"https://timjden.github.io/cinc_assignment/27//#testresult/8f5c565baa8038d8","status":"failed","statusDetails":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55b8883b62c3 <unknown>\n#1 0x55b8881bf83a <unknown>\n#2 0x55b8881f8985 <unknown>\n#3 0x55b8881f8b61 <unknown>\n#4 0x55b888230d14 <unknown>\n#5 0x55b888216f6d <unknown>\n#6 0x55b88822ea50 <unknown>\n#7 0x55b888216d63 <unknown>\n#8 0x55b8881eb7e3 <unknown>\n#9 0x55b8881eca21 <unknown>\n#10 0x55b88840418e <unknown>\n#11 0x55b888407622 <unknown>\n#12 0x55b8883eaaae <unknown>\n#13 0x55b8884082a3 <unknown>\n#14 0x55b8883deecf <unknown>\n#15 0x55b888428588 <unknown>\n#16 0x55b888428706 <unknown>\n#17 0x55b8884428b2 <unknown>\n#18 0x7ff9e8e8f609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x55b8883b62c3 <unknown>\n#1 0x55b8881bf83a <unknown>\n#2 0x55b8881f8985 <unknown>\n#3 0x55b8881f8b61 <unknown>\n#4 0x55b888230d14 <unknown>\n#5 0x55b888216f6d <unknown>\n#6 0x55b88822ea50 <unknown>\n#7 0x55b888216d63 <unknown>\n#8 0x55b8881eb7e3 <unknown>\n#9 0x55b8881eca21 <unknown>\n#10 0x55b88840418e <unknown>\n#11 0x55b888407622 <unknown>\n#12 0x55b8883eaaae <unknown>\n#13 0x55b8884082a3 <unknown>\n#14 0x55b8883deecf <unknown>\n#15 0x55b888428588 <unknown>\n#16 0x55b888428706 <unknown>\n#17 0x55b8884428b2 <unknown>\n#18 0x7ff9e8e8f609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","time":{"start":1667413847209,"stop":1667413857582,"duration":10373}},{"uid":"fd4ac7d4e7aa535e","reportUrl":"https://timjden.github.io/cinc_assignment/26//#testresult/fd4ac7d4e7aa535e","status":"failed","statusDetails":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5646a5dba2c3 <unknown>\n#1 0x5646a5bc383a <unknown>\n#2 0x5646a5bfc985 <unknown>\n#3 0x5646a5bfcb61 <unknown>\n#4 0x5646a5c34d14 <unknown>\n#5 0x5646a5c1af6d <unknown>\n#6 0x5646a5c32a50 <unknown>\n#7 0x5646a5c1ad63 <unknown>\n#8 0x5646a5bef7e3 <unknown>\n#9 0x5646a5bf0a21 <unknown>\n#10 0x5646a5e0818e <unknown>\n#11 0x5646a5e0b622 <unknown>\n#12 0x5646a5deeaae <unknown>\n#13 0x5646a5e0c2a3 <unknown>\n#14 0x5646a5de2ecf <unknown>\n#15 0x5646a5e2c588 <unknown>\n#16 0x5646a5e2c706 <unknown>\n#17 0x5646a5e468b2 <unknown>\n#18 0x7f9c4df18609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x5646a5dba2c3 <unknown>\n#1 0x5646a5bc383a <unknown>\n#2 0x5646a5bfc985 <unknown>\n#3 0x5646a5bfcb61 <unknown>\n#4 0x5646a5c34d14 <unknown>\n#5 0x5646a5c1af6d <unknown>\n#6 0x5646a5c32a50 <unknown>\n#7 0x5646a5c1ad63 <unknown>\n#8 0x5646a5bef7e3 <unknown>\n#9 0x5646a5bf0a21 <unknown>\n#10 0x5646a5e0818e <unknown>\n#11 0x5646a5e0b622 <unknown>\n#12 0x5646a5deeaae <unknown>\n#13 0x5646a5e0c2a3 <unknown>\n#14 0x5646a5de2ecf <unknown>\n#15 0x5646a5e2c588 <unknown>\n#16 0x5646a5e2c706 <unknown>\n#17 0x5646a5e468b2 <unknown>\n#18 0x7f9c4df18609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","time":{"start":1667413661907,"stop":1667413672249,"duration":10342}},{"uid":"cb6b6841bec744cc","reportUrl":"https://timjden.github.io/cinc_assignment/25//#testresult/cb6b6841bec744cc","status":"passed","time":{"start":1667413413324,"stop":1667413430917,"duration":17593}},{"uid":"90bd9f2d78c5f1ac","reportUrl":"https://timjden.github.io/cinc_assignment/24//#testresult/90bd9f2d78c5f1ac","status":"passed","time":{"start":1667412771914,"stop":1667412789538,"duration":17624}},{"uid":"532c3c2e9bcedda9","reportUrl":"https://timjden.github.io/cinc_assignment/23//#testresult/532c3c2e9bcedda9","status":"failed","statusDetails":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5566378172c3 <unknown>\n#1 0x55663762083a <unknown>\n#2 0x556637659985 <unknown>\n#3 0x556637659b61 <unknown>\n#4 0x556637691d14 <unknown>\n#5 0x556637677f6d <unknown>\n#6 0x55663768fa50 <unknown>\n#7 0x556637677d63 <unknown>\n#8 0x55663764c7e3 <unknown>\n#9 0x55663764da21 <unknown>\n#10 0x55663786518e <unknown>\n#11 0x556637868622 <unknown>\n#12 0x55663784baae <unknown>\n#13 0x5566378692a3 <unknown>\n#14 0x55663783fecf <unknown>\n#15 0x556637889588 <unknown>\n#16 0x556637889706 <unknown>\n#17 0x5566378a38b2 <unknown>\n#18 0x7f93c8083609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x5566378172c3 <unknown>\n#1 0x55663762083a <unknown>\n#2 0x556637659985 <unknown>\n#3 0x556637659b61 <unknown>\n#4 0x556637691d14 <unknown>\n#5 0x556637677f6d <unknown>\n#6 0x55663768fa50 <unknown>\n#7 0x556637677d63 <unknown>\n#8 0x55663764c7e3 <unknown>\n#9 0x55663764da21 <unknown>\n#10 0x55663786518e <unknown>\n#11 0x556637868622 <unknown>\n#12 0x55663784baae <unknown>\n#13 0x5566378692a3 <unknown>\n#14 0x55663783fecf <unknown>\n#15 0x556637889588 <unknown>\n#16 0x556637889706 <unknown>\n#17 0x5566378a38b2 <unknown>\n#18 0x7f93c8083609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","time":{"start":1667412548599,"stop":1667412558911,"duration":10312}}]}}